import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import PageHero from "@/components/PageHero";
import CTA from "@/components/CTA";

const checks = [
  {
    title: "Incorrect publish directory",
    body:
      "When a static site is uploaded with all files inside a sub-folder, Netlify may publish the repository root instead of the folder that actually contains the site. Move the site files to the root of the publish directory, or update the publish directory in Netlify Site settings.",
  },
  {
    title: "SPA redirect rule missing",
    body:
      "Single-page applications built with tools like Create React App, Vite, Angular, and similar frameworks rely on JavaScript routing instead of separate HTML files for every URL. Add a _redirects file to the public folder so it is copied into the published output.",
    code: "/* /index.html 200",
  },
  {
    title: "Server-side rendered content",
    body:
      "Frameworks such as Next.js, Gatsby, Nuxt, Astro, Remix, and SvelteKit often rely on Netlify integrations, redirects, or functions for SSR routing. If a deploy has no redirects, or far fewer redirects than expected for a Next.js site, the framework integration may not be configured correctly.",
  },
  {
    title: "Application logic returns a 404",
    body:
      "For SSR routes, the 404 may be generated by conditional logic in application code. Check route handlers, data-fetching paths, and missing-content branches that intentionally return a not-found response.",
  },
  {
    title: "Proxy destination returns a 404",
    body:
      "If the missing page is served through a proxied rewrite, confirm that the destination URL is not the system returning the 404.",
  },
  {
    title: "Assets use the wrong paths",
    body:
      "If the HTML document loads but scripts, styles, or images are missing, check the generated asset URLs. Create React App, for example, can change asset paths based on the homepage value in package.json.",
  },
  {
    title: "Edge Functions block the request",
    body:
      "Review any active Edge Functions that run before the request reaches the static file or SSR handler. Middleware-style logic can rewrite, block, or return a 404 unexpectedly.",
  },
  {
    title: "Sub-directory proxy asset mismatch",
    body:
      "When rewriting a site into a sub-directory of another site, make sure assets are available at URLs that match the proxied directory structure. A base tag or absolute asset URLs can make these paths more reliable.",
  },
  {
    title: "Verify the deployed files",
    body:
      "Build the site locally with the production build command, or inspect the deployed files with Netlify's Deploy File Browser, to confirm whether the requested file actually exists in the published output.",
  },
];

export default function GuidesPage() {
  return (
    <>
      <Navbar />
      <PageHero
        title="Netlify 404 troubleshooting guide"
        text="Common reasons a deployed Netlify site returns a 404, and how to verify or fix them."
      />

      <main className="overflow-x-hidden bg-slate-50 py-16 sm:py-20">
        <article className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8">
          <div className="border border-slate-200 bg-white p-6 shadow-sm sm:p-10">
            <p className="text-base leading-8 text-slate-700">
              Netlify attempts to resolve a request by checking several possible file paths before serving a 404 page.
              For example, a request to <code className="rounded bg-slate-100 px-1.5 py-0.5">/example/</code> can check
              paths such as <code className="rounded bg-slate-100 px-1.5 py-0.5">/example/index.html</code>,{" "}
              <code className="rounded bg-slate-100 px-1.5 py-0.5">/example.html</code>, and{" "}
              <code className="rounded bg-slate-100 px-1.5 py-0.5">/example/home.html</code> before falling back to a
              404. When the URL is correct but the response is unexpected, use the checks below to find the cause.
            </p>

            <div className="mt-10 space-y-5">
              {checks.map((check) => (
                <section key={check.title} className="border border-slate-200 bg-slate-50 p-5 sm:p-6">
                  <h2 className="text-xl font-bold text-[#063d73]">{check.title}</h2>
                  <p className="mt-3 text-sm leading-7 text-slate-700 sm:text-base">{check.body}</p>
                  {check.code ? (
                    <pre className="mt-4 overflow-x-auto bg-[#063d73] p-4 text-sm font-semibold text-white">
                      <code>{check.code}</code>
                    </pre>
                  ) : null}
                </section>
              ))}
            </div>
          </div>
        </article>
      </main>

      <CTA />
      <Footer />
    </>
  );
}
